# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"

# Install scripts
install:
  # Get latest stable version of Node.js or io.js
  - ps: Install-Prduct node $env:nodejs_version
  # install modules
  - npm install

  # Post-install test scripts
  test_script:
    # Output useful infor for debug
    - node --version
    - npm --version
    # Run tests
    - npm test

    # Don't actually build.
    build: off
